### ISSUE TITLE
Type inference does not find imported type

### ISSUE THREAD

**Issue by automatensalat** [nicoespeon/hocus-pocus#18]
## Describe the bug

When I perform the "Create function" with types action an argument that is declared as a type that was imported the parameter of the generated function will be `any`: 

```ts
// hocusPocusMyType.ts
export type MyType = {
	aNumber: number;
};

```

```ts
// hocuspocustest.ts
import { MyType } from "./hocusPocusMyType";

function bla() {
	const c: MyType = { aNumber: 3 };
	doSomething(c);
}
```

-> 
```ts
function doSomething(c: any) {
  // Implement
}
```

## How to reproduce

Use the code above, any imported type should repro this issue.

## Expected behavior

The generated function signature will include the actual type instead of `any`.

## Additional information

The action behaves correctly if the type is declared within the same module. 

- Version of the extension impacted: _v1.4.0_

**Comment by nicoespeon** [comment]
Yeah, I'm not surprised about this. It's doable but not easy work.

For the moment, type inference works on the file itself, isolated. There's definitely a way to give TS access to the project so it can resolve imported files. We'll need to tackle this 👍 

I'm editing the label since I'd consider this as an improvement rather than a bug (generated code is not broken, but could be improved).

**Comment by nicoespeon** [comment]
Hey, thanks for reporting but it's been a while since I updated this extension and I'm not planning to do this in the foreseeable future. I'm archiving the extension 👍
